version: '3.1'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      #- ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    entrypoint: "/usr/bin/odoo -c/etc/odoo/odoo.conf"
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-web-data:
  odoo-db-data:
secrets:
  postgresql_password:
    file: odoo_pg_pass
